/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/App/Footer.vue')['default']
    AppNavbar: typeof import('./components/App/Navbar.vue')['default']
    My: typeof import('./components/My.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionExperience: typeof import('./components/Section/Experience.vue')['default']
    SectionHero: typeof import('./components/Section/Hero.vue')['default']
    SectionProjects: typeof import('./components/Section/Projects.vue')['default']
    SectionTechnology: typeof import('./components/Section/Technology.vue')['default']
  }
}
