/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooterFooter: typeof import('./components/App/Footer/Footer.vue')['default']
    AppNavbarNavbar: typeof import('./components/App/Navbar/Navbar.vue')['default']
    'Blog-[id]': typeof import('./pages/blog/[id].vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionExperience: typeof import('./components/Section/Experience.vue')['default']
    SectionHero: typeof import('./components/Section/Hero.vue')['default']
    SectionProjects: typeof import('./components/Section/Projects.vue')['default']
    SectionTechnology: typeof import('./components/Section/Technology.vue')['default']
    SectionWrapperWrapper: typeof import('./components/Section/Wrapper/Wrapper.vue')['default']
  }
}
